### ISSUE TITLE
timeBucket

### ISSUE THREAD

**Issue by vgoklani** [redis-porto/redistimeseries-airquality#1]
Hey there - is the timeBucket in seconds or milliseconds?

    baseline_values = redis_obj.execute_command(
        "TS.RANGE",
        used_key,
        baseline_date_unix_ts,
        baseline_end_date_unix_ts,
        "AGGREGATION",
        args.agg_type,
        args.bucket_size_seconds,
    )

it looks like you've defined it in seconds, but the documentation says milliseconds?

https://oss.redislabs.com/redistimeseries/commands/#tsrange

thanks!

**Comment by filipecosta90** [comment]
hi there @vgoklani, when this article was written the time unit was seconds. will correct it to be up to data. thanks.
kind regards,
